flasky/app/data_analysis/__init__.py
#coding=utf-8

from flask import Blueprint

data_analysis = Blueprint('data_analysis',__name__)

from . import views

flasky/app/data_analysis/views.py
#coding=utf-8


from flask import render_template, redirect, request, url_for, flash,jsonify
from flask_login import login_user,logout_user,login_required
from ..models import User,handle_mysql
from . import data_analysis
# from .forms import LoginForm, RegistrationForm
from datetime import datetime
# from flasky.app import db

handle_mysql=handle_mysql()

import random
data = [random.randint(0,100) for i in range(5)]

@data_analysis.route('/DataAnalysis')
@login_required
def DataAnalysis():

    return render_template('data_analysis/data_index.html',current_time=datetime.utcnow(),
                           ldata=[random.randint(0,100) for i in range(5)],
                           sdata=[random.randint(0,100) for i in range(5)],
                           xdata=[random.randint(0,100) for i in range(5)],
                           xiaoliang=[random.randint(0,100) for i in range(6)]
                           )




@data_analysis.route('/daili')
# @login_required
def daili():
    if request.method=="POST":
        return 'ok'
    return render_template('data_analysis/daili.html')


data=[600, 200, 360, 100, 150, 200]
@data_analysis.route('/j')
# @login_required
def json_data():
    # return 1
    return jsonify(data)
    # return render_template('data_analysis/daili.html')


#重设密码
@data_analysis.route('/posthtml', methods=['GET', 'POST'])
def posthtml():

    # if form.validate_on_submit():
    if request.method=='POST':
        form=request.form
        # user = User.query.filter_by(email=form.email.data).first()
        # if user:
        print form
            # token = user.generate_reset_token()
            # text=render_template('auth/email/reset_password.txt',user=user,token=token)
            # yibu_send_email(title=u'reset',text=text,to_userlist=[form.email.data])
            # next=request.args.get('next')
            # print next

            # send_email(user.email, 'Reset Your Password',
            #            'auth/email/reset_password',
            #            user=user, token=token,
            #            next=request.args.get('next'))
        # flash('An email with instructions to reset your password has been '
        #       'sent to you.')
        # return redirect(url_for('auth.login'))
        return 'Successful!'
    return u'链接...'



# @data_analysis.route('/')
# def index():
#     return render_template('index.html')

flasky/app/templates/data_analysis/data_index.html
{% extends "base.html" %}

<!--浏览器地址栏的图标-->
{% block head %}
  {{ super() }}<!--保留基模板中的定义的块的原始内容-->

    <script src="{{ url_for('static', filename = 'echarts.min.js') }}"></script>

{% endblock %}
<!--浏览器地址栏的图标结束-->

{% block title %}分析图{% endblock %}


{% block content %}
<div class="container">

    {% block page_content %}
    <div class="page-header">
        <!--测试登入-->

        <h2>您好！
          {% if current_user.is_authenticated %}
        {{ current_user.username }}
        {% else %}
        想查看更多内容,请登入...
        {% endif %}!
        </h2>
        <!--测试登入结束-->

        <p>The local date and time is {{ moment(current_time).format('LLL') }}.</p>
        <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>
        <div id="main2" style="width: 600px;height:400px;background-color: grey;"></div>
        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
        <div id="container1" style="width: 600px;height:400px;background-color: grey;" ></div>

        <script type="text/javascript">
            // 基于准备好的dom，初始化echarts实例
            var myChart = echarts.init(document.getElementById('main2'));

            // 指定图表的配置项和数据
            var option = {
                title: {
                    text: '销量分析'
                },
                tooltip: {},
                legend: {
                    data:['销量']
                },
                xAxis: {
                    data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                },
                yAxis: {},
                series: [{
                    name: '销量',
                    type: 'bar',
                    data: {{xiaoliang}},//[5, 20, 36, 10, 10, 20]
                }]
            };

            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
    </script>
        <script type="text/javascript">
                var dom = document.getElementById("container1");
                var myChart = echarts.init(dom);
                var app = {};
                option = null;
                option = {
                    title: {
                    text: '推广分析'
                },
                    series : [
                        {
                            name: '访问来源',
                            type: 'pie',
                            radius: '55%',
                            data:[
                                {value:235, name:'视频广告'},
                                {value:274, name:'联盟广告'},
                                {value:310, name:'邮件营销'},
                                {value:335, name:'直接访问'},
                                {value:400, name:'搜索引擎'}
                            ]
                        }
                    ]
                };;
                if (option && typeof option === "object") {
                    myChart.setOption(option, true);
                }
       </script>

        <hr/>

        <!-- 实现个性化设置-->
        <div id="container2" style="width: 600px;height:400px;background-color: grey;" ></div>
        <script type="text/javascript">
                var dom = document.getElementById("container2");

                var myChart = echarts.init(dom);

                option = null;
//                ldata='{{ldata[0]}}';

                option = {
                    title: {
                                text: '推广分析 '
                            },

                    backgroundColor: '#2c343c',  //设置背景颜色
                    textStyle: {    //设置文本的样式
                                color: 'rgba(255, 255, 255, 1)'
                            },

                //也可以每个系列分别设置，每个系列的文本设置在 label.normal.textStyle。

                //跟itemStyle一样，label和labelLine的样式也有normal和emphasis两个状态。
                label: {
                    normal: {
                        textStyle: {
                            color: 'rgba(255, 255, 255, 0.3)'
                        }
                    }
                },
                //饼图的话还要将标签的视觉引导线的颜色设为浅色。
//                labelLine: {
//                    normal: {
//                        lineStyle: {
//                            color: 'rgba(255, 255, 255, 0.3)'
//                        }
//                    }
//                },


                    series : [
                        {
                            name: '访问来源',
                            type: 'pie',
                            roseType: 'angle',//<!--必须使用以上的饼图才行通过设置 roseType 显示成南丁格尔图。-->
                            radius: '55%',
                            itemStyle: {   //加上阴影效果
                                            normal: {
                                                // 阴影的大小
                                                shadowBlur: 200,
                                                // 阴影水平方向上的偏移
                                                shadowOffsetX: 0,
                                                // 阴影垂直方向上的偏移
                                                shadowOffsetY: 0,
                                                // 阴影颜色
                                                shadowColor: 'rgba(0, 0, 0, 0.5)'
                                            },
                                            //emphasis是鼠标 hover 时候的高亮样式。这个示例里是正常的样式下加阴影，但是可能更多的时候是 hover 的时候通过阴影突出。
                                            emphasis: {
                                                    shadowBlur: 200,
                                                    shadowColor: 'rgba(255, 255, 255, 0)'
                                                }
                                            },


                            data:[
                                {   value:'{{ldata[0]}}',
                                    name:'视频广告',
                                    itemStyle: {
                                        normal: {
                                                color: 'gold'
                                        }
                                     }

                                },
                                {value:'{{ldata[1]}}', name:'联盟广告'},
                                {value:'{{ldata[2]}}', name:'邮件营销'},
                                {value:'{{ldata[3]}}', name:'直接访问',
                                    //但是这次因为只有明暗度的变化，所以有一种更快捷的方式是通过 visualMap 组件将数值的大小映射到明暗度。
                                    visualMap: {
                                        // 不显示 visualMap 组件，只用于明暗度的映射
                                        show: false,
                                        // 映射的最小值为 80
                                        min: 80,
                                        // 映射的最大值为 600
                                        max: 600,
                                        inRange: {
                                            // 明暗度的范围是 0 到 1
                                            colorLightness: [0, 1]
                                        }
                                    },

                                },
                                {   value:'{{ldata[4]}}',
                                    name:'搜索引擎',
                                    itemStyle: {
                                        normal: {
                                                color: '#4CD10A'
                                        }
                                     }
                                }
                            ]
                        }
                    ]
                };
                if (option && typeof option == "object") {
                    //使用刚指定的配置项和数据显示图表
                    myChart.setOption(option, true);

                }
       </script>

        <!--实现异步加载-->
        <div id="container3" style="width: 600px;height:400px;background-color: grey;" ></div>
        <script type="text/javascript">

                var myChart = echarts.init(document.getElementById("container3"));
                // 显示标题，图例和空的坐标轴
                myChart.setOption({
                    title: {
                        text: '异步数据加载示例'
                    },
                    tooltip: {},
                    legend: {
                        data:['销量']
                    },
                    xAxis: {
                        data: []
                    },
                    yAxis: {},
                    series: [{
                        name: '销量',
                        type: 'bar',
                        data: []
                    }]
                });
                data=null;
                // 异步加载数据
                console.log("{{ url_for('.json_data') }}");
                $.get("{{ url_for('.json_data') }}").done(function () {
                    // 填入数据
                    myChart.setOption({
                        xAxis: {
                            data: '{{xdata}}',//data.categories
                        },
                        series: [{
                            // 根据名字对应到相应的系列
                            name: '销量',
                            data: '{{sdata}}',//[5, 20, 36, 10, 10, 20]//data.data
                        }]
                    });
                });



//            var data = {
//                "name": "test",
//                "age", 1
//            }
//            $.ajax({
//                type: 'POST',
//                url: "{{ url_for('data_analysis.json_data') }}",///your/url/,
//                data: JSON.stringify(data), //# 转化为字符串
//                contentType: 'application/json; charset=UTF-8',
//                dataType: 'json', //# 注意：这里是指希望服务端返回json格式的数据
//                success: function(data) { //# 这里的data就是json格式的数据
//                },
//                error: function(xhr, type) {
//                }
//            });


        </script>



    </div>


    {% endblock %}
</div>

<div>

    <div style="width:100px; height:100px; border:1px solid #ccc;">
        <a href="#">111111</a>
    </div>

    <script>

    //    alert(oDiv.innerHTML);   //这样就可以获取div标签里面所有的内容。
        var oDiv = document.getElementsByTagName('div')[0];
//        var last=JSON.stringify(oDiv.innerHTML);
        var last=oDiv.innerHTML;
//        alert(oDiv.innerHTML);   //这样就可以获取div标签里面所有的内容。

        function post(url, params) {
            var tempForm = document.createElement("form");
            tempForm.action = url;
            tempForm.method = "post";
            tempForm.style.display = "none";
            for (var x in params) {
                var opt = document.createElement("textarea");
                opt.name = x;
                opt.value = params[x];
                // alert(opt.name)
                tempForm.appendChild(opt);
            }
            document.body.appendChild(tempForm);
            tempForm.submit();
            return tempForm;
        }

        //调用方法
        post('http://172.16.1.159:5000/data_analysis/_add_numbers', {username : last, password : 'yyyy'});

    </script>

</div>



{% endblock %}

flasky/app/templates/data_analysis/ditu.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="百度地图,百度地图API，百度地图自定义工具，百度地图所见即所得工具" />
    <meta name="description" content="百度地图API自定义地图，帮助用户在可视化操作下生成百度地图" />
    <title>百度地图API自定义地图</title>
    <!--引用百度地图API-->
    <!--<script type="text/javascript" src="http://api.map.baidu.com/api?v=2.0&ak=您的密匙"></script>-->
  <script type="text/javascript" src="http://api.map.baidu.com/api?key=46ce9d0614bf7aefe0ba562f8cf87194&v=1.0&services=false"></script>

  </head>

  <body>
    <!--百度地图容器-->
    <div style="width:700px;height:550px;border:#ccc solid 1px;font-size:12px" id="map"></div>
    <p style="color:red;font-weight:600">地图生成工具基于百度地图JS api v2.0版本开发，使用请申请密匙。
      <a href="http://developer.baidu.com/map/index.php?title=jspopular/guide/introduction" style="color:#2f83c7" target="_blank">了解如何申请密匙</a>
      <a href="http://lbsyun.baidu.com/apiconsole/key?application=key" style="color:#2f83c7" target="_blank">申请密匙</a>
    </p>
  </body>
  <script type="text/javascript">
    //创建和初始化地图函数：
    function initMap(){
      createMap();//创建地图
      setMapEvent();//设置地图事件
      addMapControl();//向地图添加控件
      addMapOverlay();//向地图添加覆盖物
    }
    function createMap(){
      map = new BMap.Map("map");
      map.centerAndZoom(new BMap.Point(116.597469,34.585924),7);
    }
    function setMapEvent(){
      map.enableScrollWheelZoom();
      map.enableKeyboard();
      map.enableDragging();
      map.enableDoubleClickZoom()
    }
    function addClickHandler(target,window){
      target.addEventListener("click",function(){
        target.openInfoWindow(window);
      });
    }
    function addMapOverlay(){
      var markers = [
        {content:"备注1",title:"扬州小区1",imageOffset: {width:0,height:3},position:{lat:34.787289,lng:114.196621}},
        {content:"我的标记2",title:"标记2",imageOffset: {width:0,height:3},position:{lat:34.630609,lng:114.004599}},
        {content:"我的备注",title:"我的标记",imageOffset: {width:0,height:3},position:{lat:35.01276,lng:113.980453}}
      ];



      for(var index = 0; index < markers.length; index++ ){
        var point = new BMap.Point(markers[index].position.lng,markers[index].position.lat);
        var marker = new BMap.Marker(point,{icon:new BMap.Icon("http://api.map.baidu.com/lbsapi/createmap/images/icon.png",new BMap.Size(20,25),{
          imageOffset: new BMap.Size(markers[index].imageOffset.width,markers[index].imageOffset.height)
        })});
        var label = new BMap.Label(markers[index].title,{offset: new BMap.Size(25,5)});
        var opts = {
          width: 200,
          title: markers[index].title,
          enableMessage: false
        };
        var infoWindow = new BMap.InfoWindow(markers[index].content,opts);
        marker.setLabel(label);
        addClickHandler(marker,infoWindow);
        map.addOverlay(marker);
      };
      var plOpts = [
        {strokeColor:"#f00",strokeWeight:"4",strokeOpacity:"1"}
      ];
      var plPath = [
        [
          new BMap.Point(114.983106,35.112979),
          new BMap.Point(115.217671,34.775905),
          new BMap.Point(115.015301,34.460297),
          new BMap.Point(114.592163,34.116705),
          new BMap.Point(114.081638,34.204647),
          new BMap.Point(114.06784,34.216111),
          new BMap.Point(114.06784,34.216111),
          new BMap.Point(114.06784,34.216111)
        ],
      ];
      for(var index = 0; index < plOpts.length; index++){
        var polyline = new BMap.Polyline(plPath[index],plOpts[index]);
        map.addOverlay(polyline);
      }
    }
    //向地图添加控件
    function addMapControl(){
      var scaleControl = new BMap.ScaleControl({anchor:BMAP_ANCHOR_BOTTOM_LEFT});
      scaleControl.setUnit(BMAP_UNIT_IMPERIAL);
      map.addControl(scaleControl);
      var navControl = new BMap.NavigationControl({anchor:BMAP_ANCHOR_TOP_LEFT,type:BMAP_NAVIGATION_CONTROL_LARGE});
      map.addControl(navControl);
      var overviewControl = new BMap.OverviewMapControl({anchor:BMAP_ANCHOR_BOTTOM_RIGHT,isOpen:true});
      map.addControl(overviewControl);
    }
    var map;
      initMap();
  </script>
</html>

flasky/app/templates/data_analysis/test.html
{% extends "base.html" %}

<!--浏览器地址栏的图标-->
{% block head %}
  {{ super() }}<!--保留基模板中的定义的块的原始内容-->

    <script src="{{ url_for('static', filename = 'echarts.min.js') }}"></script>

{% endblock %}
<!--浏览器地址栏的图标结束-->

{% block title %}分析图{% endblock %}


{% block content %}
<div class="container">

    {% block page_content %}
    <div class="page-header">
        <!--测试登入-->

        <h2>您好！
          {% if current_user.is_authenticated %}
        {{ current_user.username }}
        {% else %}
        想查看更多内容,请登入...
        {% endif %}!
        </h2>
        <!--测试登入结束-->

        <p>The local date and time is {{ moment(current_time).format('LLL') }}.</p>
        <p>That was {{ moment(current_time).fromNow(refresh=True) }}</p>








        <hr/>
        <div id="main2" style="width: 600px;height:400px;background-color: grey;"></div>
        <!-- 为ECharts准备一个具备大小（宽高）的Dom -->
        <div id="container1" style="width: 600px;height:400px;background-color: grey;" ></div>

        <script type="text/javascript">
            // 基于准备好的dom，初始化echarts实例
            var myChart = echarts.init(document.getElementById('main2'));

            // 指定图表的配置项和数据
            var option = {
                title: {
                    text: '销量分析'
                },
                tooltip: {},
                legend: {
                    data:['销量']
                },
                xAxis: {
                    data: ["衬衫","羊毛衫","雪纺衫","裤子","高跟鞋","袜子"]
                },
                yAxis: {},
                series: [{
                    name: '销量',
                    type: 'bar',
                    data: [5, 20, 36, 10, 10, 20]
                }]
            };

            // 使用刚指定的配置项和数据显示图表。
            myChart.setOption(option);
    </script>
        <script type="text/javascript">
                var dom = document.getElementById("container1");
                var myChart = echarts.init(dom);
                var app = {};
                option = null;
                option = {
                    title: {
                    text: '推广分析'
                },
                    series : [
                        {
                            name: '访问来源',
                            type: 'pie',
                            radius: '55%',
                            data:[
                                {value:235, name:'视频广告'},
                                {value:274, name:'联盟广告'},
                                {value:310, name:'邮件营销'},
                                {value:335, name:'直接访问'},
                                {value:400, name:'搜索引擎'}
                            ]
                        }
                    ]
                };;
                if (option && typeof option === "object") {
                    myChart.setOption(option, true);
                }
       </script>

    </div>


    {% endblock %}
</div>
{% endblock %}